// FUNCTION EK REUSEBLE BLOCK OF CODE HOTA HAI
// EK BAAR CODE LIKHO AUR JITNE BAAR CHAO USE KARO 

// REAL LIFE EXAMPLE

// SOCHO MUMMY ROJ CHAI BNATI HAI

// STEP
//  PANI GRAM
//  CHAI PATTI DAALO
//  DOODH DAALO
// CHEENI DAALO

// HAR BAAR YE STEP DOBAARA LIKHNE KI JAHGH HUM IS PROCESS KO EK NAAM DE SKTE HAI
// MAKE TEA()

// JAB CHAI CHAIYE 
// MAKE TEA() KO CALL KARO

